package org.springframework.mongo.support;

import com.mongodb.BasicDBObject;
import com.mongodb.DBObject;
import com.mongodb.MongoException;
import com.mongodb.WriteResult;
import org.bson.types.ObjectId;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.dao.IncorrectUpdateSemanticsDataAccessException;
import org.springframework.mongo.UncategorizedMongoException;

/**
 * Helper class that provides static methods to ease work with the mongo-related stuff such as ID extraction,
 * creating query object with the mongo ID field and so on.
 *
 * @author Alexander Shabanov
 */
public final class MongoUtil {

    /**
     * Default name of the mongo's primary key field.
     */
    public static final String ID = "_id";


    /**
     * Creates an instance of the {@link BasicDBObject} with the preinitialized mongo id field.
     * This may be useful in the 'get-by-id' queries to create query object with the given id value.
     * The provided identifier is expected to be retrieved from the previously executed insert method which
     * return mongo's ObjectId as a plain string value.
     * This method also reinterprets the provided string as {@link ObjectId} value.
     *
     * @param id String identifier, previously generated by mongo, reinterpreted as {@link ObjectId}.
     * @return An instance of the {@link BasicDBObject} with the preinitialized {@code _id} field
     */
    public static BasicDBObject withId(String id) {
        return new BasicDBObject()
                .append(ID, new ObjectId(id, false));
    }

    public static String extractId(DBObject dbObject) {
        final Object idObject = dbObject.get(ID);
        if (idObject == null) {
            throw new DataIntegrityViolationException("No ID field in dbObject=" + dbObject);
        } else if (idObject instanceof ObjectId) {
            return ((ObjectId) idObject).toStringMongod();
        }

        throw new DataIntegrityViolationException("Unrecognized ID field in dbObject=" + dbObject);
    }

    public static WriteResult executeWriteOperation(MongoWriteOperation writeOperation) {
        try {
            final WriteResult result = writeOperation.execute();
            final MongoException mongoException = result.getLastError().getException();
            if (mongoException != null) {
                throw mongoException;
            }

            return result;
        } catch (MongoException.DuplicateKey e) {
            throw new DuplicateKeyException("Mongo PK violation", e);
        } catch (MongoException e) {
            throw new UncategorizedMongoException("Unable to insert new record", e);
        }
    }

    public static void expectOneUpdate(WriteResult result) {
        if (result.getN() == 0) {
            throw new IncorrectUpdateSemanticsDataAccessException("Update failed: " +
                    "expecting to update exactly one record, result=" + result);
        }
    }

    private MongoUtil() {}
}
